# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

variables:
  imageRepository: '$(repositoryName)/backend-api.dev'
  containerRegistry: '$(registryName)'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build_and_push
  displayName: Build backend api
  jobs:
    - job: Build
      pool:
        vmImage: $(vmImageName)
      steps:
      - task: Docker@2
        displayName: "build"
        inputs:
          containerRegistry: 'Container Registry'
          repository: '$(imageRepository)'
          command: 'build'
          Dockerfile: '$(dockerfilePath)'
          tags: '$(tag)'
          arguments: '--build-arg SENDGRID=$(sendGrid) --build-arg KEY=$(Key) --build-arg BOILERPLATE=$(boilerPlate) --build-arg BLOB_STORAGE_KEY=$(blob_storage_key)'

      - task: Docker@2
        displayName: "push" 
        inputs:
          containerRegistry: 'Container Registry'
          repository: '$(imageRepository)'
          command: 'push'
          tags: '$(tag)'
